name: Publish to Thunderstore

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Collect build info
        id: info
        shell: pwsh
        run: |
          $shaShort = git rev-parse --short HEAD
          "sha_short=$shaShort" >> $env:GITHUB_OUTPUT
          [xml]$project = Get-Content ResoniteBetterIMESupport.csproj
          $version = $project.Project.PropertyGroup.Version
          "version=$version" >> $env:GITHUB_OUTPUT
          "Version found: $version"
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"
      - name: Install Cake Tool
        run: dotnet tool restore
      - name: Build with Cake
        run: dotnet cake --target=Build --verbosity=normal
      - name: Publish to Thunderstore
        shell: pwsh
        run: |
          $zipFile = Get-ChildItem ./build/*.zip | Select-Object -First 1
          dotnet tcli publish --file $zipFile.FullName
        env:
          TCLI_AUTH_TOKEN: ${{ secrets.TCLI_AUTH_TOKEN }}